### PR TITLE
include uploadDuration in complete upload requests.

### LINKED ISSUE #116: Missing uploadDuration parameter
### Expected Behaviour

AEM can analyze approximate file transfer rates via its log messages. For this to work, clients must provide the `uploadDuration` parameter in complete upload calls.

### Actual Behaviour

The module does not include `uploadDuration` in its complete upload calls. So any clients using `node-httptransfer` do not provide the information necessary to calculate transfer rates.

### Reproduce Scenario (including but not limited to)

Using the `AEMUpload` class to transfer files to AEM.

#### Steps to Reproduce

Run the `AEM upload then download` e2e test, and note that the log messages in AEM do not include the upload duration.

#### Platform and Version

macOS version 11.6.5
node-httptransfer version 3.2.0

#### Sample Code that illustrates the problem

See `AEM upload then download` e2e test.

#### Logs taken while reproducing problem

N/A

### PR DESCRIPTION
**Pull request by mfrisbey**
## Description

Modifies the module so that the `uploadDuration` parameter is included when uploading files to AEM with `AEMUpload`.

This was an interesting fix because we need to know how much time elapsed between when an asset started to transfer and when it finished. I couldn't find a single location where all this information is available, because everything is happening in parallel. To get the _actual_ time elapsed, I modified `Transfer` so that it informs the controller whenever a new part begins transferring. The controller checks to see if the asset to which the part belongs is already transferring; if not, the controller records the start time of the asset. `TransferPartsJoin` knows when all the parts for an asset have finished transferring, so when that happens it retrieves the start time from the controller and sets the transfer duration on the `TransferAsset`. Finally, `AEMCompleteUpload` uses the duration from the `TransferAsset` to send the asset's `uploadDuration` to AEM's complete upload servlet.

Fixes #116 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: lib/controller/transfercontroller.js [hunk 1]
```diff
@@ -225,6 +226,31 @@ class TransferController extends EventEmitter {
...
     }
+
+    /**
+     * Informs the controller that the transfer for a given part has begun.
+     *
+     * @param {TransferPart} part Part that is now transferring.
+     */
+    transferringPart(part) {
+        const { transferAsset } = part;
+        if (!this.transferringAssets.has(transferAsset)) {
```
Comment (tmathern) [inline lib/controller/transfercontroller.js:237]: Do we need to use the full object or could we use any kind of id?

**Review by tmathern — APPROVED** [review]
Note `Date.getTime` and `Date.now` are equivalent (second is slightly shorter to write).

**Comment by tmathern** [comment]
Added @aleenaniklaus as reviewer, since AAL also uses this library.

File: lib/controller/transfercontroller.js (hunk 1 above)
Comment (mfrisbey) [reply lib/controller/transfercontroller.js:237]: We could try using the URL of the asset. Is there a performance impact to using the full object?

Comment (tmathern) [reply lib/controller/transfercontroller.js:237]: Not performance, I'm just wondering what having two equal transferAssets means. According to the documentation [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness#same-value-zero_equality), it would check references of the objects. Is this good enough here?

File: lib/asset/transferasset.js [hunk 2]
```diff
@@ -215,6 +215,26 @@ class TransferAsset {
...
 
+    /**
+     * Sets the total amount of time, in milliseconds, that it took for the asset to transfer
+     * in its entirety.
+     *
+     * @param {number} duration Number of milliseconds.
+     */
+    setUploadDuration(duration) {
+        this[PRIVATE].uploadDuration = duration;
+    }
```
Comment (bobvanmanen) [inline lib/asset/transferasset.js:226]: This should be a `setter` equivalent to the getter below.

File: lib/controller/transfercontroller.js (hunk 1 above)
Comment (bobvanmanen) [reply lib/controller/transfercontroller.js:237]: I think you can track this in `TransferAsset` by storing the transfer start time in the object, it doesn't need to be tracked in the controller.

File: lib/asset/transferasset.js (hunk 2 above)
Comment (bobvanmanen) [reply lib/asset/transferasset.js:226]: I would add a setter/getter here to record the transfer start time. Transfer would need to check if a start time is already recorded, if not then set one otherwise ignore it.

File: lib/functions/transferpartsjoin.js [hunk 3]
```diff
@@ -78,6 +78,11 @@ class JoinTransferParts extends AsyncGeneratorFunction {
                 // check if the transfer has been completed
                 const contentLength = transferPart.metadata.contentLength;
                 if (isComplete(completedRanges, contentLength)) {
+                    const startTime = controller.getTransferStartTime(transferAsset);
+                    if (startTime) {
+                        const uploadDuration = new Date().getTime() - startTime;
+                        transferAsset.setUploadDuration(uploadDuration);
+                    }
```
Comment (bobvanmanen) [inline lib/functions/transferpartsjoin.js:85]: This can then be `transferAsset.getStartTime()` and calculate the duration the same way.

**Review by bobvanmanen — CHANGES_REQUESTED** [review]

**Comment by mfrisbey** [comment]
@bobvanmanen thanks for a second set of eyes. Sometimes that helps simplify a solution 😂 

Will you please take another look and let me know what you think?

File: lib/index.js [hunk 4]
```diff
@@ -30,5 +32,7 @@ module.exports = {
     uploadAEMMultipartFile,
     getResourceHeaders,
     AEMUpload,
-    AEMDownload
+    AEMDownload,
+    BlockUpload,
+    BlockDownload
```
Comment (mfrisbey) [inline lib/index.js:37]: @tmathern @pheenomenon FYI, I noticed that tests in `e2e/blocktransfer.test.js` were failing. Adding these as exports fixed the failures.

Comment (tmathern) [reply lib/index.js:37]: ack, thanks!

File: lib/asset/transferasset.js [hunk 5]
```diff
@@ -215,6 +215,61 @@ class TransferAsset {
...
+        this[PRIVATE].transferStart = startTime;
+    }
+
+    /**
+     * Retrieves the timestamp of when the asset finished transferring. Will be 0 if no
+     * end time is available.
+     *
+     * @returns {number} Timestamp.
+     */
+    get transferEndTime() {
```
Comment (aleenaniklaus) [inline lib/asset/transferasset.js:244]: Should `transferEndTime` be added to the constructor?

**Review by aleenaniklaus — APPROVED** [review]
Thanks for this work! Looks good to me, just left a small question in `transferasset.js`.

File: lib/asset/transferasset.js (hunk 5 above)
Comment (aleenaniklaus) [reply lib/asset/transferasset.js:244]: I suppose if there's never a check for 0 or null specifically (we only check falsy), we don’t need to add it to the constructor. I can't really think of a use case without looking through the repo a bit more. No concerns on my end, thanks for this work!!

Comment (mfrisbey) [reply lib/asset/transferasset.js:244]: > we only check falsy

`0`, `null`, and `undefined` will all be treated as `false` in a falsy check, so both of those would end up as `0` for the return value.

**Review by bobvanmanen — APPROVED** [review]
LGTM
