### PR TITLE
fix issues when using module in a browser.

### LINKED ISSUE #69: Module unable to be used in browser
### Expected Behaviour

This module is a dependency of [aem-upload](https://github.com/adobe/aem-upload), which supports being used in both Node.JS and browsers.

### Actual Behaviour

 There are several issues that prevent `node-httptransfer` from working correctly in a browser:

* An error message from simply requiring the module. The message is along the lines of `TypeError: Cannot destructure property 'dirname' of '__webpack_require__(...).posix' as it is undefined.`
* When using `AEMUpload`, passing a `blob` as an element of an object passed in `uploadFiles` is ignored, even though it's called out as supported in the method [documentation](https://github.com/adobe/node-httptransfer/blob/7ec8f925b6595898ddadf52ca6f0989cb42a8579/lib/aem/aemupload.js#L74).
* Requests sent using `fetch` don't work as expected.

### Reproduce Scenario (including but not limited to)

Attempt to use `aem-upload` in a React application.

#### Steps to Reproduce

For my case, I did the following:

* Used `create-react-app` to initialize a new React application.
* Ran `npm install @adobe/aem-upload` to add `aem-upload` as a dependency of my application.
* Wrote code using `aem-upload`'s examples to upload an asset in conjunction with an HTML `file` input and the `blob` option.
* Observed failures in the upload process.

#### Platform and Version

* macOS 11.6 Big Sur
* `aem-upload` version 1.1.4
* `node-httptransfer` version 2.7.1

#### Sample Code that illustrates the problem

```
// note that this is a code snippet from my React application.
// "this.state.selectedFile" contains the "File" object provided by an
//  HTML "file" input
const uploadFiles = [{
  fileName: this.state.selectedFile.name,
  fileSize: this.state.selectedFile.size,
  blob: this.state.selectedFile,
}];

const upload = new DirectBinary.DirectBinaryUpload();
const options = new DirectBinary.DirectBinaryUploadOptions()
  .withUrl('https://<REDACTED>/content/dam')
  .withBasicAuth('<REDACTED>')
  .withUploadFiles(uploadFiles);

const result = await upload.uploadFiles(options);
```

#### Logs taken while reproducing problem

N/A

### PR DESCRIPTION
**Pull request by mfrisbey**
## Description

Provides various changes to allow this module to be used in both a browser and Node.JS context:

* Refactor usage of `posix` from the `path` module, since it's not available when run in a browser.
* Support passing a `blob` option when uploading files with `AEMUpload`.
* Fix cases where the module was assuming the response body of a request would always be a stream; it's not a stream when running in a browser.
* Changed so that `window.fetch` is used instead of `node-fetch-npm` when running in a browser. `node-fetch-npm` was only designed to run in Node.JS, so it wasn't working correctly in this case.

Fixes #69 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- ~[ ] My change requires a change to the documentation.~
- ~[ ] I have updated the documentation accordingly.~
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mfrisbey** [comment]
Note that I'm running some tests on Windows to make sure that the path handling still works as expected. Will update the PR if additional changes needed.

File: lib/aem/aemupload.js [hunk 1]
```diff
@@ -33,6 +33,7 @@ const { RandomFileAccess } = require("../randomfileaccess");
 const EventEmitter = require("events");
 const UploadError = require("./upload-error");
 const { FilterFailedAssets } = require("../functions/filterfailedassets");
+const { IllegalArgumentError } = require('../error');
```
Comment (tmathern) [inline lib/aem/aemupload.js:36]: Nitpick: to be consistent with the other imports, single quotes should be turned into double-quotes.
```suggestion
const { IllegalArgumentError } = require("../error");
```

File: lib/aem/aemupload.js [hunk 2]
```diff
@@ -43,7 +44,16 @@ const { FilterFailedAssets } = require("../functions/filterfailedassets");
  */
 async function* generateAEMUploadTransferRecords(options) {
     for (const uploadFile of options.uploadFiles) {
-        const sourceUrl = fileUrl(uploadFile.filePath);
+        let sourceUrl = uploadFile.blob;
+        if (!sourceUrl) {
+            if (!uploadFile.filePath) {
+                throw new IllegalArgumentError(
+                    'Either blob or filePath must be provided in uploadFiles',
+                    JSON.stringify(uploadFile),
```
Comment (tmathern) [inline lib/aem/aemupload.js:52]: eslint may complain about this if the last comma is not removed:
```suggestion
                    JSON.stringify(uploadFile)
```

File: lib/fetch.js [hunk 3]
```diff
@@ -138,6 +147,40 @@ async function stream(method, url, options) {
...
+ *
+ * @param {String} method HTTP method of the request to submit.
+ * @param {String} url URL of the request to submit.
+ * @param {Object} options Additional options to provide to fetch when
+ *  submitting the request.
+ * @returns {*} HTTP response of the request.
+ */
+async function handleStream(method, url, options) {
+    const response = await stream(method, url, options);
+    if (response.body && response.body.on) {
```
Comment (tmathern) [inline lib/fetch.js:169]: Can response be undefined/null?
```suggestion
    if (response && response.body && response.body.on) {
```

**Review by tmathern — APPROVED** [review]
Some smaller changes - but otherwise LGTM.

Where were the errors observed?

File: lib/aem/aemupload.js (hunk 1 above)
Comment (mfrisbey) [reply lib/aem/aemupload.js:36]: Good catch on the quotes, I'll fix those.

File: lib/aem/aemupload.js (hunk 2 above)
Comment (mfrisbey) [reply lib/aem/aemupload.js:52]: It didn't complain, but I'll remove the comma anyway.

File: lib/fetch.js (hunk 3 above)
Comment (mfrisbey) [reply lib/fetch.js:169]: I think we'd have bigger problems downstream if it were, but I'll add the check anyway to be safe.

**Comment by tmathern** [comment]
Do all the browsers supported have fetch now? Even the older ones?

**Comment by mfrisbey** [comment]
> @tmathern Do all the browsers supported have fetch now? Even the older ones?

It appears that the modern browsers [support it](https://caniuse.com/fetch). There are some edge cases that don't, but IMO what we have should be sufficient for the vast majority of cases.

After some testing on windows, I opted to [remove posix entirely](https://github.com/adobe/node-httptransfer/pull/70/files#diff-3fb720f70ea34fb2975fd6c38ac4b6b6131373be2abfa4760dfaae8a25daaee2R175), and just replace all occurrences of `\` with `/` when needing a URL path. Admittedly, I don't understand the original motivation for using `posix`, so I wanted to get a second opinion on that particular change. My testing showed that this strategy was more robust on Windows, making it so that either `/` or `\` will work. WDYT?

File: lib/asset/asset.js [hunk 4]
```diff
@@ -13,7 +13,8 @@
 "use strict";
 
 require("core-js/stable");
-const { dirname: urlPathDirname, basename: urlPathBasename } = require("path").posix;
+const { basename: filePathBasename } = require("path");
```
Comment (bobvanmanen) [inline lib/asset/asset.js:16]: @mfrisbey I picked `posix` with the thought that it would behave the same whether it runs on Windows or Mac. Technically on Windows the path separator is `\` and not `/` which is the separator in urls. It looks like you already verified this though.

**Review by bobvanmanen — APPROVED** [review]

**Comment by bobvanmanen** [comment]
Just to bring it up, but how do we ensure going forward that this keeps working on Node.js Mac, Node.js Windows, and in modern browsers? It seems easy to break unless we keep manually testing it which doesn't scale.

**Comment by tmathern** [comment]
@bobvanmanen @mfrisbey 
More on integration than unit tests side:
There is a headless scriptable browser, [pahntomJS](https://phantomjs.org/) that can be used to do simple testing. Otherwise, there is Selenium to automate Chrome/Safari/Edge (Chrome has a headless version too). But I don't think any UI validation is needed here, just the workings without UI-related updates.

**Comment by mfrisbey** [comment]
> @bobvanmanen how do we ensure going forward that this keeps working on Node.js Mac, Node.js Windows, and in modern browsers?

Here are some of my thoughts:

* Ideally, it would be awesome if the repo's CI could run a set of e2e tests on different images (i.e. Mac, Windows, and a browser). Unfortunately, the complexity of setting up an instance of AEM to test against may prevent this unless we somehow set up a dedicated cloud environment that the tests can run against.
* A slightly less optimal solution could be to set up some tests (similar to [aem-upload](https://github.com/adobe/aem-upload/tree/master/e2e)) that are run locally before creating PRs. A single set of node.js tests could be run on Mac/Windows, and we could create some kind of simple React application that could be run to test basic browser support.
* As a bare minimum, I added more unit tests that cover the issues that I fixed in this PR, so there is at least better unit test coverage for the browser case now.
